name: Supabase Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: v2   # or 'latest'

      - name: Login to Supabase
        run: supabase login --token "${{ secrets.SUPABASE_ACCESS_TOKEN }}" --no-browser

      - name: Link project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      # Push migrations when you push to main
      - name: Deploy migrations
        if: github.event_name == 'push'
        run: supabase db push

      # Spin up preview DB for each PR
      - name: Create preview branch (PRs)
        if: github.event_name == 'pull_request'
        run: |
          supabase db branch create pr-${{ github.event.number }}
          supabase db push --db-url "$(supabase db branch url pr-${{ github.event.number }})"
